[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "MSEP"
version = "0.0.1"
authors = [
  { name="Chuanming DONG", email="donghuanming@yahoo.com" },
]
description = "A pipeline for extracting patients' medical status information from clinical documents"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/DongChuanming/MSEP"
Issues = "https://github.com/DongChuanming/MSEP/issues"



